### ISSUE TITLE
show image: Dead kernel

### ISSUE THREAD

**Issue by gecko17k** [Jackson-Kang/Pytorch-VAE-tutorial#2]
Hey Jackson, thanks for this.
Very nice.

I'm wondering why this kills my kernel "Dead kernel" after this

`show_image(x, idx=0)`

it was working just fine until this cell killed it.

```
model.eval()

with torch.no_grad():
    for batch_idx, (x, _) in enumerate(tqdm(test_loader)):
        x = x.view(batch_size, x_dim)
        x = x.to(DEVICE)
        
        x_hat, _, _ = model(x)


        break
```
So, I tested every line and more and more of it, no trouble until the entire cell worked just fine.
However, now ,2 cells down kills it:
`show_image(x, idx=0)
`
I'm really confused about this.

Setup: PC, CPU (no GPU, so cuda=False), Anaconda, Chrome, Python 3.9.7, Windows 10 Enterprise, 64 bit, RAM= 32.0 GB.
I'm running the Jupyter notebook through the organisation's servers on this PC.

Thanks.

**Comment by Jackson-Kang** [comment]
Hello, @gecko17k .
First of all, thank you for raising this issue.

You are using organisation's server, so the problem is not related with your  PC.
To know what exactly the trouble is, could you check that which code is problematic in the "show_image" function?

Thanks.
